# Generated by Django 5.0.2 on 2025-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_analyst_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='vxn_index',
            field=models.FloatField(blank=True, help_text='VXN (NASDAQ-100 Volatility Index) at analysis time', null=True),
        ),
    ]
