# Generated by Django 5.2.1 on 2025-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_vxn_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNewsQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(default='Finlight', max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('ticker_symbol', models.CharField(db_index=True, help_text='Stock ticker this article relates to', max_length=10)),
                ('article_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Webhook News Queue',
                'verbose_name_plural': 'Webhook News Queue',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', '-received_at'], name='api_webhook_status_dc314b_idx'), models.Index(fields=['ticker_symbol', 'status'], name='api_webhook_ticker__c32bbb_idx')],
            },
        ),
    ]
