# Generated by Django 5.2.1 on 2025-11-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_webhook_news_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCVTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Tick timestamp (second precision)')),
                ('price', models.DecimalField(decimal_places=4, help_text='Price at this tick', max_digits=12)),
                ('volume', models.IntegerField(default=0, help_text='Volume at this tick')),
                ('bid', models.DecimalField(blank=True, decimal_places=4, help_text='Bid price', max_digits=12, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=4, help_text='Ask price', max_digits=12, null=True)),
                ('source', models.CharField(default='eodhd_ws', help_text='Data source (eodhd_ws, etc.)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_ticks', to='api.ticker')),
            ],
            options={
                'verbose_name': 'OHLCV Tick',
                'verbose_name_plural': 'OHLCV Ticks',
                'db_table': 'api_ohlcv_tick',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='WebhookNewsQueue',
        ),
        migrations.AddIndex(
            model_name='ohlcvtick',
            index=models.Index(fields=['ticker', '-timestamp'], name='api_ohlcv_t_ticker__32d5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvtick',
            index=models.Index(fields=['-timestamp'], name='api_ohlcv_t_timesta_e329c1_idx'),
        ),
    ]
