# Generated by Django 5.2.1 on 2025-11-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ohlcvtick_delete_webhooknewsqueue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='The second this snapshot represents')),
                ('ohlc_1sec_open', models.DecimalField(decimal_places=4, help_text='Open price for this second', max_digits=12)),
                ('ohlc_1sec_high', models.DecimalField(decimal_places=4, help_text='High price for this second', max_digits=12)),
                ('ohlc_1sec_low', models.DecimalField(decimal_places=4, help_text='Low price for this second', max_digits=12)),
                ('ohlc_1sec_close', models.DecimalField(decimal_places=4, help_text='Close price for this second', max_digits=12)),
                ('ohlc_1sec_volume', models.IntegerField(default=0, help_text='Total volume for this second')),
                ('ohlc_1sec_tick_count', models.IntegerField(default=0, help_text='Number of ticks in this second')),
                ('price_momentum_5sec', models.FloatField(blank=True, help_text='5-second price momentum', null=True)),
                ('price_change_1sec', models.FloatField(blank=True, help_text='1-second price change %', null=True)),
                ('composite_score', models.FloatField(blank=True, help_text='Real-time composite score (-100 to +100)', null=True)),
                ('news_score_cached', models.FloatField(blank=True, help_text='Cached news score from latest AnalysisRun', null=True)),
                ('technical_score_cached', models.FloatField(blank=True, help_text='Cached technical score', null=True)),
                ('source', models.CharField(default='eodhd_ws', help_text='Data source', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_snapshots', to='api.ticker')),
            ],
            options={
                'verbose_name': 'Second Snapshot',
                'verbose_name_plural': 'Second Snapshots',
                'db_table': 'api_second_snapshot',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ticker', '-timestamp'], name='api_second__ticker__ef47f3_idx'), models.Index(fields=['-timestamp'], name='api_second__timesta_9797bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TickCandle100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_number', models.IntegerField(db_index=True, help_text='Sequential candle number (1st, 2nd, 3rd...)')),
                ('completed_at', models.DateTimeField(db_index=True, help_text='When 100th tick arrived')),
                ('open', models.DecimalField(decimal_places=4, help_text='Open price (1st tick)', max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, help_text='High price (max of 100 ticks)', max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, help_text='Low price (min of 100 ticks)', max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, help_text='Close price (100th tick)', max_digits=12)),
                ('total_volume', models.IntegerField(help_text='Total volume of 100 ticks')),
                ('first_tick_time', models.DateTimeField(help_text='Timestamp of 1st tick in this candle')),
                ('last_tick_time', models.DateTimeField(help_text='Timestamp of 100th tick in this candle')),
                ('duration_seconds', models.FloatField(help_text='Duration in seconds (last - first tick)')),
                ('source', models.CharField(default='eodhd_ws', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_candles_100', to='api.ticker')),
            ],
            options={
                'verbose_name': '100-Tick Candle',
                'verbose_name_plural': '100-Tick Candles',
                'db_table': 'api_tick_candle_100',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['ticker', '-completed_at'], name='api_tick_ca_ticker__aaa2d5_idx'), models.Index(fields=['ticker', 'candle_number'], name='api_tick_ca_ticker__060439_idx'), models.Index(fields=['-completed_at'], name='api_tick_ca_complet_bf0156_idx')],
                'unique_together': {('ticker', 'candle_number')},
            },
        ),
    ]
